name: cycles
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - make
  - gxx
  - clang
  - doxygen
  - spdlog
  - sfml
  - pip 
  - pip:
    - breathe
    - sphinx
    - sphinx_rtd_theme
