name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Tweak dependency file
      # Run only in OSX and Win, remove libudev from the dependencies
      if: ${{ runner.os }} != 'Linux'
      run: |
        sed -i '/libudev/d' environment.yml
      
    - name: Show dependency file
      run: cat environment.yml
      
    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: false
        cache-downloads: true
    
    - name: List environment
      run: |
        micromamba activate cycles
        micromamba list
    
    - name: Configure and compile the library
      run: |
        micromamba activate cycles
        if [ "${{ runner.os }}" == "Linux" ]; then
          # Fix sfml bug (Linux only)
          ln -s $CONDA_PREFIX/lib/libudev.so.1 $CONDA_PREFIX/lib/libudev.so.0
        fi
        mkdir build && cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -G Ninja ..
        cmake --build .
                
    - name: Run tests
      run: |
        micromamba activate cycles
        cd build
        ctest --output-on-failure
